version: '3.8'
services:
  go-api:
    container_name: interact-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    networks:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: interact-postgres-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: interact-redis-db
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data

volumes:
  postgres:
    name: postgres-db
    driver: local
  redis:
    name: redis-db
    driver: local