version: '3.8'

networks:
  backend-network:
    driver: bridge

services:
  go-api:
    container_name: interact-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:${PORT}
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./log:/app/log/
      - ./database:/app/database/
    networks:
      - backend-network

  postgres:
    container_name: interact-postgres-db
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 5432:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/app/database/
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis
    container_name: interact-redis-db
    restart: always
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "-a", "${REDIS_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres:
    name: postgres-db
    driver: local
