package config

const (
	SENDER_NAME  = "Interact"
	SENDER_EMAIL = "prathamm0409@gmail.com"
	TEMPLATE_DIR = "templates/"

	GMAIL_SENDER = "socials.interact@gmail.com"
)

const (
	EARLY_ACCESS_MAIL              = -1
	ACCOUNT_VERIFICATION_MAIL      = 0
	WELCOME_MAIL                   = 1
	OTP_VERIFICATION_MAIL          = 2
	ACCOUNT_DEACTIVATION_OTP_MAIL  = 3
	FORGOT_PASSWORD_MAIL           = 4
	NEW_CHAT_REQUEST_MAIL          = 10
	NEW_ACTIVITIES_MAIL            = 20
	LONG_TIME_NO_SEE_MAIL          = 21
	NEWSLETTER_MAIL                = 22
	FLAGGED_COMMENT_MAIL           = 50
	FLAGGED_POST_MAIL              = 51
	FLAGGED_PROJECT_MAIL           = 52
	FLAGGED_OPENING_MAIL           = 53
	FLAGGED_EVENT_MAIL             = 54
	FLAGGED_ANNOUNCEMENT_MAIL      = 55
	FLAGGED_POLL_MAIL              = 56
	REVOKED_COMMENT_FLAG_MAIL      = 70
	REVOKED_POST_FLAG_MAIL         = 71
	REVOKED_PROJECT_FLAG_MAIL      = 72
	REVOKED_OPENING_FLAG_MAIL      = 73
	REVOKED_EVENT_FLAG_MAIL        = 74
	REVOKED_ANNOUNCEMENT_FLAG_MAIL = 75
	REVOKED_POLL_FLAG_MAIL         = 76
)
